CREATE TABLE IF NOT EXISTS rm_participants (
  rm_participant_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  institution ENUM('unach', 'cobach') NOT NULL,
  first_name VARCHAR(120) NOT NULL,
  last_name_paternal VARCHAR(120) NOT NULL,
  last_name_maternal VARCHAR(120) NOT NULL,
  birthdate DATE NOT NULL,
  age TINYINT UNSIGNED NOT NULL,
  gender VARCHAR(30) NOT NULL,
  curp VARCHAR(18) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  state_name VARCHAR(120) NOT NULL,
  city_name VARCHAR(120) NOT NULL,
  semester VARCHAR(8) NOT NULL,
  unach_unit VARCHAR(255) NULL,
  unach_major VARCHAR(180) NULL,
  cobach_campus VARCHAR(180) NULL,
  cobach_area VARCHAR(180) NULL,
  responsiva_file_path VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (rm_participant_id),
  KEY rm_idx_institution (institution),
  KEY rm_idx_email (email),
  KEY rm_idx_curp (curp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
