CREATE TABLE IF NOT EXISTS rm_participant_submissions (
  rm_submission_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  participant_id BIGINT UNSIGNED NOT NULL,
  institution ENUM('unach', 'cobach') NOT NULL,
  unach_unit VARCHAR(255) NULL,
  unach_semester VARCHAR(8) NULL,
  unach_major VARCHAR(180) NULL,
  unach_first_name VARCHAR(120) NULL,
  unach_last_name_1 VARCHAR(120) NULL,
  unach_last_name_2 VARCHAR(120) NULL,
  unach_birthdate DATE NULL,
  unach_age TINYINT UNSIGNED NULL,
  unach_gender VARCHAR(30) NULL,
  unach_curp VARCHAR(18) NULL,
  unach_email VARCHAR(190) NULL,
  unach_phone VARCHAR(30) NULL,
  unach_state VARCHAR(120) NULL,
  unach_city VARCHAR(120) NULL,
  cobach_campus VARCHAR(180) NULL,
  cobach_semester VARCHAR(8) NULL,
  cobach_area VARCHAR(180) NULL,
  cobach_first_name VARCHAR(120) NULL,
  cobach_last_name_1 VARCHAR(120) NULL,
  cobach_last_name_2 VARCHAR(120) NULL,
  cobach_birthdate DATE NULL,
  cobach_age TINYINT UNSIGNED NULL,
  cobach_gender VARCHAR(30) NULL,
  cobach_curp VARCHAR(18) NULL,
  cobach_email VARCHAR(190) NULL,
  cobach_phone VARCHAR(30) NULL,
  cobach_state VARCHAR(120) NULL,
  cobach_city VARCHAR(120) NULL,
  cobach_responsiva_path VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (rm_submission_id),
  UNIQUE KEY rm_submission_participant_unique (participant_id),
  KEY rm_submission_institution_idx (institution),
  CONSTRAINT rm_submission_participant_fk FOREIGN KEY (participant_id) REFERENCES rm_participants (rm_participant_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
